# Configuration file template for go-api
# Copy this file to config.yaml and customize for your environment
# 
# IMPORTANT: 
# - config.yaml is ignored by git for security
# - All configuration is in this single file - no environment variables needed
# - Just copy this file to config.yaml and update the values

# Database configuration
database:
  url: 'postgres://username:password@localhost:5432/database_name'
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: '1h'

# Security configuration  
security:
  jwt_secret: 'your-super-secret-jwt-key-here-minimum-32-characters'
  jwt_expiry: '24h'
  headers_enabled: true
  trusted_proxies: ''

# Application configuration
app:
  port: '8000'
  environment: 'development'
  read_timeout: '30s'
  write_timeout: '30s'
  idle_timeout: '120s'
  shutdown_timeout: '10s'

# CORS configuration
cors:
  allowed_origins: 'http://localhost:3000'
  allowed_methods: 'GET,POST,PUT,DELETE,OPTIONS'
  allowed_headers: 'Origin,Content-Type,Accept,Authorization'

# Rate limiting configuration
rate_limit:
  enabled: true
  max: 100
  window: '1m'

# Logging configuration
logging:
  dir: 'storage/logs'
  max_size: 10485760 # 10MB in bytes
  max_age: 30 # days
  enable_daily: true
