# Configuration file template for go-api
# Copy this file to config.yaml and customize for your environment
#
# IMPORTANT:
# - config.yaml is ignored by git for security
# - All configuration is in this single file - no environment variables needed
# - Just copy this file to config.yaml and update the values

# Database configuration
database:
  url: "postgres://username:password@localhost:5432/database_name?sslmode=require"
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: "1h"

# Security configuration
security:
  jwt_secret: "" # MUST BE SET - Generate a strong, random JWT secret (minimum 32 characters)
  jwt_expiry: "24h"
  headers_enabled: true
  trusted_proxies: ""

# Application configuration
app:
  port: "8000"
  environment: "production" # Use 'development' only for development
  timezone: "UTC" # Timezone for the application (e.g., Asia/Jakarta, UTC, America/New_York, Europe/London)
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  shutdown_timeout: "10s"

# CORS configuration
cors:
  allowed_origins: "https://yourdomain.com" # Change to your domain
  allowed_methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed_headers: "Origin,Content-Type,Accept,Authorization"

# Rate limiting configuration
rate_limit:
  enabled: true
  max: 100
  window: "1m"

# Logging configuration
logging:
  enable_database_log: false # Set true to see database queries
  enable_app_log: false # Set true to see application requests
  level: "info" # info, debug, warn, error

# Mail configuration
mail:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@example.com"
  password: "your-app-password"
  from_name: "Go API App"
  from_email: "noreply@example.com"
